version: "1"
services:
  backend:
    restart: always
    build: ./heron-api
    ports:
      - "4015:4015"
    environment:
      - PORT=4015
      - MONGODB_URL=mongodb://db:27018/heron
    depends_on:
      - db
  db:
    image: mongo
    command: mongod --port 27018
    volumes:
      - mongodata:/data/heron
  interface:
    restart: always
    container_name: heron-interface
    build:
      context: ./heron-interface
      args:
        VITE_REACT_APP_BASE_URL: http://api-heronbooking.tk
    ports:
      - "4025:4025"
    environment:
      - PORT=4025
  nginx-react:
    container_name: ngixreactapp
    build: 
     context: .
     args:
      REACT_APP_BASE_URL: http://api-heronbooking.tk
    ports:
      - 80:80
      - 9000:9000
      - "3001:3001"
    environment:
      NODE_ENV: production
      
    depends_on:
      - backend
      - interface
volumes:
  mongodata:
