version: "1"
services:
  backend:
    restart: always
    build: ./heron-api
    ports:
      - "4015:4015"
    environment:
      - PORT=4015
      - MONGODB_URL=mongodb://db:27018/heron
    depends_on:
      - db
  db:
    image: mongo
    command: mongod --port 27018
    volumes:
      - mongodata:/data/heron
  interface:
    restart: always
    container_name: heron-interface
    build: ./heron-interface
    ports:
      - "4025:4025"
  # nginx-react:
  #   container_name: ngixreactapp
  #   build: .
  #   ports:
  #     - 80:80
  #   environment:
  #     NODE_ENV: production
  #   depends_on:
  #     - backend
  #     - interface
volumes:
  mongodata:
