version: "1"
services:
  api-cleverbooking.prod:
    container_name: api-cleverbooking.prod
    restart: always
    build: ./heron-api
    ports:
      - "4015:4015"
    environment:
      - PORT=4015
      - MONGODB_URL=mongodb://db:27018/heron-prod
      - MOMO_IPN_URL=http://api-cleverbooking.tk/api/payment/ipn
      - MOMO_REDIRECT_URL=http://cleverbooking.tk/payment/ipn
      - EMAIL_SMTP_USERNAME=caothien029@gmail.com
      - EMAIL_SMTP_PASSWORD=rwluxppwcrsuxlfy
    depends_on:
      - db
    volumes:
      - uploads:/app/heron-api/public/uploads
  db:
    image: mongo
    container_name: mongodb
    command: mongod --port 27018
    ports:
      - "27018:27018"
    volumes:
      - mongodata:/data/heron
  cleverbooking.prod:
    restart: always
    container_name: cleverbooking.prod
    build:
      context: ./heron-interface
      args:
        VITE_REACT_APP_BASE_URL: http://api-cleverbooking.tk
    ports:
      - "4025:4025"
    environment:
      - PORT=4025
  api-heronbooking.prod:
    restart: always
    container_name: api-heronbooking.prod
    build: ./heron-api
    ports:
      - "3015:3015"
    environment:
      - PORT=3015
      - MONGODB_URL=mongodb://db:27018/heron-dev
      - MOMO_IPN_URL=http://api-heronbooking.tk/api/payment/ipn
      - MOMO_REDIRECT_URL=http://heronbooking.tk/payment/ipn
      - EMAIL_SMTP_USERNAME=caothien029@gmail.com
      - EMAIL_SMTP_PASSWORD=rwluxppwcrsuxlfy
    volumes:
      - uploads-testing:/app/heron-api/public/uploads
  heronbooking.prod:
    restart: always
    container_name: heronbooking.prod
    build:
      context: ./heron-interface
      args:
        VITE_REACT_APP_BASE_URL: http://api-heronbooking.tk
    ports:
      - "3025:3025"
    environment:
      - PORT=3025
  nginx-react:
    container_name: ngixreactapp
    build: 
     context: .
     args:
      REACT_APP_BASE_URL: http://api-cleverbooking.tk
      REACT_APP_BASE_URL_TESING: http://api-heronbooking.tk
    ports:
      - 80:80
      - 9000:9000
      - 3001:3001
    environment:
      NODE_ENV: production
    depends_on:
      - api-cleverbooking.prod
      - cleverbooking.prod
      - api-heronbooking.prod
      - heronbooking.prod
volumes:
  mongodata:
  uploads-testing:
  uploads:
