version: "1"
services:
  api.bookingheron.com:
    container_name: api.bookingheron.com
    restart: always
    build: ./heron-api
    ports:
      - "4015:4015"
    environment:
      - PORT=4015
      - MONGODB_URL=mongodb://db:27018/heron
      - MOMO_IPN_URL=http://api-heronbooking.tk/api/payment/ipn
      - MOMO_REDIRECT_URL=http://heronbooking.tk/payment/ipn
      - EMAIL_SMTP_USERNAME=caothien029@gmail.com
      - EMAIL_SMTP_PASSWORD=rwluxppwcrsuxlfy
    depends_on:
      - db
  db:
    image: mongo
    container_name: mongodb
    command: mongod --port 27018
    ports:
      - "27018:27018"
    volumes:
      - mongodata:/data/heron
  bookingheron.com:
    restart: always
    container_name: bookingheron.com
    build:
      context: ./heron-interface
      args:
        VITE_REACT_APP_BASE_URL: http://api.cleverbooking.prod
    ports:
      - "4025:4025"
    environment:
      - PORT=4025
  test-api.bookingheron.com:
    restart: always
    container_name: test-api.bookingheron.prod
    build: ./heron-api
    ports:
      - "3015:3015"
    environment:
      - PORT=3015
      - MONGODB_URL=mongodb://db:27018/heron-dev
  test.bookingheron.com:
    restart: always
    container_name: test.bookingheron.prod
    build:
      context: ./heron-interface
      args:
        VITE_REACT_APP_BASE_URL: http://test-api.cleverbooking.prod
    ports:
      - "3025:3025"
    environment:
      - PORT=3025
  nginx-react:
    container_name: ngixreactapp
    build: 
     context: .
     args:
      REACT_APP_BASE_URL: http://api-cleverbooking.prod
      REACT_APP_BASE_URL_TESING: http://test-api-cleverbooking.prod
    ports:
      - 80:80
      - 9000:9000
      - 3001:3001
    environment:
      NODE_ENV: production
    depends_on:
      - api.bookingheron.com
      - bookingheron.com
      - test-api.bookingheron.com
      - test.bookingheron.com
volumes:
  mongodata:
